"""
Django settings for xibbar_tech project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables du fichier .env (uniquement en local)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# ---------------------------------------------------------------------------
# Sécurité
# ---------------------------------------------------------------------------

# DEBUG est actif en local, désactivé sur Render
DEBUG = 'RENDER' not in os.environ

# La clé secrète vient de l'environnement (.env en local, variables Render en production).
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Clé de secours valable UNIQUEMENT pour le développement local
        SECRET_KEY = 'django-insecure-cle-de-developpement-locale'
    else:
        raise ImproperlyConfigured(
            "La variable d'environnement SECRET_KEY est obligatoire en production."
        )

# Hôtes autorisés : local + adresse du site sur Render
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Render : adresse du site, pour que les formulaires (connexion, commentaires, contact) soient acceptés
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']
    # Render place le site derrière un proxy HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # allauth : construit les adresses de retour (callback Google) en https
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# Protections HTTPS : actives uniquement en production (sur Render)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600  # à augmenter plus tard quand tout fonctionne


# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_tailwind_cli',
    'django_ckeditor_5',
    'blog',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Cloudinary : stockage des images, activé seulement si les variables d'environnement existent.
CLOUDINARY_ENABLED = bool(os.environ.get('CLOUDINARY_CLOUD_NAME'))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # obligatoire pour django-allauth
]

ROOT_URLCONF = 'xibbar_tech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'xibbar_tech.wsgi.application'


# ---------------------------------------------------------------------------
# Base de données
# ---------------------------------------------------------------------------
# PostgreSQL sur Render via DATABASE_URL, MySQL en local par défaut
DATABASES = {
    'default': dj_database_url.config(
        default='mysql://root:@localhost:3306/xibbar_tech_db',
        conn_max_age=600
    )
}


# ---------------------------------------------------------------------------
# Validation des mots de passe
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------------------------------------------------------------------
# Authentification & django-allauth (connexion avec Google)
# ---------------------------------------------------------------------------

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'blog:login'
LOGIN_REDIRECT_URL = 'blog:home'
LOGOUT_REDIRECT_URL = 'blog:home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'blog:home'
SOCIALACCOUNT_LOGIN_REDIRECT_URL = 'blog:home'

# Configuration moderne : autorise à la fois le username et l'email pour vos formulaires
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SESSION_REMEMBER = True

# Liaison automatique des comptes sociaux
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Google : les identifiants viennent des variables d'environnement
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [
            {
                'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
                'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
                'key': '',
            }
        ],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# MySQL ne gère pas les contraintes d'unicité conditionnelles d'allauth :
# allauth vérifie lui-même l'unicité, on masque donc cet avertissement.
SILENCED_SYSTEM_CHECKS = ['models.W036']


# ---------------------------------------------------------------------------
# Internationalisation
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Fichiers statiques et médias
# ---------------------------------------------------------------------------
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

# Dossier où WhiteNoise regroupe les fichiers statiques pour la production
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if CLOUDINARY_ENABLED:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    # Les images envoyées vont sur Cloudinary
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }

# Chemin du programme Tailwind : uniquement sur Windows (en local)
if os.name == 'nt':
    TAILWIND_CLI_PATH = BASE_DIR / 'tailwind.exe'


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
if DEBUG:
    # En local : les emails s'affichent dans la console
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }
else:
    # En production : envoi réel par SMTP (variables à définir sur Render)
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.environ.get('EMAIL_HOST', ''),
                'username': os.environ.get('EMAIL_HOST_USER', ''),
                'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
                'port': int(os.environ.get('EMAIL_PORT', '587')),
                'use_tls': True,
            },
        },
    }


# ---------------------------------------------------------------------------
# CKEditor 5
# ---------------------------------------------------------------------------
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            # Structure
            'heading', '|',
            # Mise en forme du texte
            'bold', 'italic', 'underline', 'strikethrough',
            'subscript', 'superscript', 'highlight', '|',
            # Police et couleurs
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            # Alignement et retrait
            'alignment', 'outdent', 'indent', '|',
            # Listes et citation
            'bulletedList', 'numberedList', 'todoList', 'blockQuote', '|',
            # Médias et liens
            'link', 'imageUpload', 'mediaEmbed', 'insertTable', '|',
            # Code
            'code', 'codeBlock', 'sourceEditing', '|',
            # Outils
            'removeFormat', 'undo', 'redo',
        ],
        # Barre qui apparaît quand on clique sur une image
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight',
            ],
        },
        # Barre qui apparaît quand on clique dans un tableau
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties',
            ],
        },
        'codeBlock': {
            'languages': [
                {'language': 'python', 'label': 'Python'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'php', 'label': 'PHP'},
                {'language': 'sql', 'label': 'SQL'},
                {'language': 'bash', 'label': 'Bash'},
                {'language': 'json', 'label': 'JSON'},
            ]
        },
    }
}